### ISSUE TITLE
On MacOs, If image path has a space, the script doesn't work.

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [LeetaoGoooo/wallpaper#1]
Hi, 
On MacOs if the wallpaper path has a space in it, the execution of "macos-wallpaper" fails. Also the failure and error message is never propagated to the caller method/function.

The solution for this is to simply add single quotes around the {file_path} in line #20
```python
 return os.popen(f"{macos_wallpaper_path} set '{file_path}' --screen {screen} --scale {scale}")
```

**Comment by LeetaoGoooo** [comment]
> Hi,
> On MacOs if the wallpaper path has a space in it, the execution of "macos-wallpaper" fails. Also the failure and error message is never propagated to the caller method/function.
> 
> The solution for this is to simply add single quotes around the {file_path} in line #20
> 
> ```python
>  return os.popen(f"{macos_wallpaper_path} set '{file_path}' --screen {screen} --scale {scale}")
> ```

thank you for your comment~~
